[build]
  functions = "server"

[[headers]]
  for = "/dist/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
